### ISSUE TITLE
Error running with default values

### ISSUE THREAD

**Issue by CountZero1981** [JoeCianflone/laravel-elixir-sass-compass#8]
Hello! I'm unable to compile my scss scripts using mix.compass()
Output:

```
⇒  gulp
[21:32:48] Using gulpfile ~/workspace/airports/gulpfile.js
[21:32:48] Starting 'default'...
[21:32:48] Starting 'compass'...
[21:32:48] 'compass' errored after 580 μs
[21:32:48] TypeError: Cannot read property 'indexOf' of undefined
    at prefixOne (/home/countzero/workspace/airports/node_modules/laravel-elixir/GulpPaths.js:104:17)
    at GulpPaths.prefix (/home/countzero/workspace/airports/node_modules/laravel-elixir/GulpPaths.js:117:12)
    at GulpPaths.src (/home/countzero/workspace/airports/node_modules/laravel-elixir/GulpPaths.js:24:16)
    at prepGulpPaths (/home/countzero/workspace/airports/node_modules/laravel-elixir-sass-compass/index.js:46:14)
    at null.definition (/home/countzero/workspace/airports/node_modules/laravel-elixir-sass-compass/index.js:31:21)
    at Task.run (/home/countzero/workspace/airports/node_modules/laravel-elixir/Task.js:96:17)
    at Gulp.<anonymous> (/home/countzero/workspace/airports/node_modules/laravel-elixir/index.js:95:52)
    at module.exports (/home/countzero/workspace/airports/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/countzero/workspace/airports/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/countzero/workspace/airports/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
Error running task sequence: [TypeError: Cannot read property 'indexOf' of undefined]
[21:32:48] Finished 'default' after 5.13 ms
```

**Comment by mtpultz** [comment]
I'm encountering the same error when using: 

```
mix.compass();
```

on a clean install of Laravel 5.1 after updating to Elixir 3.0.0.  But it also fails when I try:

```
mix.compass('app.scss');
```

or

```
mix.compass('app.scss', 'public/css');
```

With this error:

```
$ gulp
[02:08:16] Using gulpfile d:\projects\project\gulpfile.js
[02:08:16] Starting 'default'...
[02:08:16] Starting 'compass'...
[02:08:16] Finished 'default' after 11 ms
[02:08:17] Compass can't find any Sass files to compile.
Is your compass configuration correct?.
If you're trying to start a new project, you have left off the directory argument.
Run "compass -h" to get help.
```

I haven't made any changes to the location of the Sass files located at /resources/assets/sass or any other changes to the default Laravel 5.1 install.

**Comment by CountZero1981** [comment]
This works fine:

```
        .compass("*", "public/css", {
            sass: "resources/assets/scss"
        })
```

This version doesn't add assets path, bugfix for this is in commits.

**Comment by liorocks** [comment]
#7 should fix this error, but i'm still waiting for the merge.

**Comment by JoeCianflone** [comment]
This should be resolved.
