### ISSUE TITLE
Compile Error Related to Accessing Elixir.Config and Elixir.Task where Undefined

### ISSUE THREAD

**Issue by mtpultz** [JoeCianflone/laravel-elixir-sass-compass#9]
I'm also having a compile error though a bit different:

```
d:\projects\project\node_modules\laravel-elixir-sass-compass\index.js:14
            javascript:  config.js.outputFolder,
                                  ^
TypeError: Cannot read property 'outputFolder' of undefined
    at Object.compass (d:\projects\project\node_modules\laravel-elixir-sass-compass\index.js:14:35)
    at d:\projects\project\gulpfile.js:20:9
    at Elixir (d:\projects\project\node_modules\laravel-elixir\index.js:3:5)
    at Object.<anonymous> (d:\projects\project\gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

It appears to affect more than one config.  If I don't use the defaults and drop in my own object with configs the error persists preventing gulp from running.  If I change config.js.outputFolder to 'public/js' the error jumps to the next issue in the config:

```
d:\projects\project\node_modules\laravel-elixir-sass-compass\index.js:20
            style:       config.css.sass.pluginOptions.outputStyle,
                                   ^
TypeError: Cannot read property 'sass' of undefined
    at Object.compass (d:\projects\project\node_modules\laravel-elixir-sass-compass\index.js:20:36)
    at d:\projects\project\gulpfile.js:20:9
    at Elixir (d:\projects\project\node_modules\laravel-elixir\index.js:3:5)
    at Object.<anonymous> (d:\projects\project\gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

So I kept going and replaced that and the next issue with the proper paths.

```
    var defaultOptions = {
            generated_images_path: false,
            config_file: false,
            javascript:  'public/js',
            sourcemap:   false,
            http_path:   false,
            relative:    true,
            comments:    true,
            require:     false,
            style:       'expanded',
            image:       config.publicPath + '/images',
            font:        config.publicPath + '/fonts',
            sass:        'resources/assets/scss',
            css:         output || config.css.outputFolder
        };
```

But then it throws an error on line 29:

```
d:\projects\project\node_modules\laravel-elixir-sass-compass\index.js:29
    new Task('compass', function() {
        ^
TypeError: undefined is not a function
    at Object.compass (d:\projects\project\node_modules\laravel-elixir-sass-compass\index.js:29:9)
    at d:\projects\project\gulpfile.js:20:9
    at Elixir (d:\projects\project\node_modules\laravel-elixir\index.js:3:5)
    at Object.<anonymous> (d:\projects\project\gulpfile.js:16:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

**Comment by mtpultz** [comment]
Looks like from your recent changes it is due to the release of Elixir 3.0.0, and I've made it passed this issue.

**Comment by Pezhvak** [comment]
Can you please tell me what to do? i have the exact problem, and i tried everything, yet it still doesn't work

**Comment by dattz** [comment]
Same problem. Any update?

**Comment by JoeCianflone** [comment]
This should have been resolved. Please make sure you're using the latest version if it isn't working paste in the error message and I'll look at it today.

**Comment by Sanovia** [comment]
C:\xampp\htdocs\Portal\node_modules\laravel-elixir-sass-compass\index.js:14
            javascript:  config.js.outputFolder,
                                  ^

TypeError: Cannot read property 'outputFolder' of undefined
    at Object.compass (C:\xampp\htdocs\Portal\node_modules\laravel-elixir-sass-compass\index.js:14:35)
    at C:\xampp\htdocs\Portal\gulpfile.js:16:9
    at Elixir (C:\xampp\htdocs\Portal\node_modules\laravel-elixir\index.js:3:5)
    at Object.<anonymous> (C:\xampp\htdocs\Portal\gulpfile.js:15:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by JoeCianflone** [comment]
@Sanovia need some more info, what versions of Elixir are you currently using?
